name: Actualizador PlutoIPTV

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          cd PlutoIPTV
          npm install request jsontoxml moment fs-extra uuid

      - name: Generar listas y EPG
        run: |
          cd PlutoIPTV
          node index.js

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Guardamos los archivos generados temporalmente en el 'stash'
          git add .
          git stash
          
          # Traemos los cambios del repo (el pull)
          git pull origin main --rebase
          
          # Recuperamos nuestros archivos generados
          git stash pop || echo "No había cambios en el stash o conflicto resuelto"
          
          # Añadimos y subimos
          git add playlist.m3u playlist_hq.m3u epg.xml
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Listas y EPG actualizados: $(date)"
            git push origin main
          else
            echo "Sin cambios para subir."
          fi
