name: Actualizador PlutoIPTV Colombia

on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecuta cada 3 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente desde la pestaña Actions
  push:
    branches: [ main ]    # Se ejecuta al hacer cambios en la rama main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Permiso crucial para que la Action pueda subir archivos

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Trae todo el historial para evitar conflictos de git

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: |
          cd PlutoIPTV
          npm install request jsontoxml moment fs-extra uuid

      - name: Generar archivos
        run: |
          cd PlutoIPTV
          node index.js
          # Movemos y forzamos la actualización de la fecha de modificación
          mv epg.xml ../
          mv playlist.m3u ../
          mv playlist_hq.m3u ../
          cd ..
          touch epg.xml playlist.m3u playlist_hq.m3u

      - name: Sincronizar y subir cambios
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Añadimos los archivos específicamente
          git add epg.xml playlist.m3u playlist_hq.m3u
          
          # Hacemos el commit. Si no hay cambios, el "|| exit 0" evita que la acción falle
          git commit -m "Actualización EPG y Listas: $(date)" || exit 0
          
          # Forzamos la subida para evitar conflictos de historial
          git push origin main --force
