name: Actualizador PlutoIPTV

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          cd PlutoIPTV
          npm install request jsontoxml moment fs-extra uuid

      - name: Generar listas y EPG
        run: |
          cd PlutoIPTV
          node index.js

      - name: Mover archivos a la raíz (Opcional)
        run: |
          # Esto mueve los archivos generados a la raíz para que el link sea más corto
          mv PlutoIPTV/playlist.m3u .
          mv PlutoIPTV/playlist_hq.m3u .
          mv PlutoIPTV/epg.xml .

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.m3u playlist_hq.m3u epg.xml PlutoIPTV/
          git commit -m "Listas y EPG actualizados: $(date)" || echo "No hay cambios para subir"
          git push
