name: Actualizar Pluto Colombia
on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch: # Botón para ejecutar manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        # El script usa: request, jsontoxml, moment, fs-extra, uuid
        run: npm install request jsontoxml moment fs-extra uuid

      - name: Generar Lista y EPG
        run: node index.js
        # El script por defecto genera 'playlist.m3u' y 'epg.xml' según tu código

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u epg.xml cache.json
          git commit -m "Actualización automática Pluto CO" || exit 0
          git push
